import test from 'node:test'
import assert from 'node:assert/strict'
import { parseTimestamp, parseTranscript, parseTranscriptAsync, findCueIndex, findWordIndex, searchCues, offsetCues, mergeCues, pickTranscriptSources, formatClock } from '../utils/transcript.js'

const VTT = `WEBVTT

NOTE generated by a test

1
00:00:01.000 --> 00:00:03.500 align:start position:0%
Harry <00:00:01.400>Potter <00:00:02.000>and the <00:00:02.800>Sorcerer&#39;s Stone

2
00:00:04.000 --> 00:00:06.000
<v Narrator>Plain &amp; simple
second line</v>

00:01:00.000 --> 00:01:02.000
<c.karaoke>Ab</c><00:01:00.500><c.karaoke>cd</c> ef
`

test('parseTimestamp handles vtt, short vtt and srt forms', () => {
  assert.equal(parseTimestamp('00:00:01.500'), 1.5)
  assert.equal(parseTimestamp('01:02:03.004'), 3723.004)
  assert.equal(parseTimestamp('02:03.5'), 123.5)
  assert.equal(parseTimestamp('00:00:01,250'), 1.25)
  assert.equal(parseTimestamp('00:00:01.05'), 1.05)
  assert.ok(Number.isNaN(parseTimestamp('nope')))
})

test('parses WebVTT cues, inline word timestamps, entities and tags', () => {
  const { cues, hasWords } = parseTranscript(VTT)
  assert.equal(hasWords, true)
  assert.equal(cues.length, 3)
  assert.equal(cues[0].text, "Harry Potter and the Sorcerer's Stone")
  assert.deepEqual(
    cues[0].words.map((w) => [w.t, w.w]),
    [
      [1, 'Harry '],
      [1.4, 'Potter '],
      [2, 'and the '],
      [2.8, "Sorcerer's Stone"]
    ]
  )
  assert.equal(cues[0].words.map((w) => w.w).join(''), cues[0].text)
  assert.equal(cues[1].text, 'Plain & simple second line')
  assert.equal(cues[1].words, null)
  assert.equal(cues[2].start, 60)
  assert.equal(cues[2].text, 'Abcd ef')
  assert.deepEqual(
    cues[2].words.map((w) => w.w),
    ['Ab', 'cd ef']
  )
})

test('parses SRT with CRLF, BOM and comma decimals', () => {
  const srt = '﻿1\r\n00:00:00,500 --> 00:00:02,000\r\nHello there\r\n\r\n2\r\n00:00:02,500 --> 00:00:04,000\r\nGeneral\r\nKenobi\r\n'
  const { cues, hasWords } = parseTranscript(srt)
  assert.equal(hasWords, false)
  assert.equal(cues.length, 2)
  assert.equal(cues[0].start, 0.5)
  assert.equal(cues[1].text, 'General Kenobi')
})

test('tolerates garbage: no trailing blank line, empty cues, bad timings, unsorted input', () => {
  assert.deepEqual(parseTranscript('').cues, [])
  const { cues } = parseTranscript('WEBVTT\n\n00:00:10.000 --> 00:00:11.000\nlate\n\nbad --> worse\nignored\n\n00:00:01.000 --> 00:00:02.000\nearly')
  assert.deepEqual(
    cues.map((c) => c.text),
    ['early', 'late']
  )
  const empty = parseTranscript('WEBVTT\n\n00:00:01.000 --> 00:00:02.000\n\n00:00:03.000 --> 00:00:04.000\nx\n')
  assert.equal(empty.cues.length, 1)
})

test('async parser matches sync parser and reports progress', async () => {
  let big = 'WEBVTT\n\n'
  for (let i = 0; i < 5000; i++) big += `00:00:${String(i % 60).padStart(2, '0')}.000 --> 00:00:${String(i % 60).padStart(2, '0')}.900\nline ${i}\n\n`
  const seen = []
  const a = await parseTranscriptAsync(big, { sliceLines: 1000, onProgress: (f) => seen.push(f) })
  const b = parseTranscript(big)
  assert.equal(a.cues.length, 5000)
  assert.deepEqual(a.cues, b.cues)
  assert.ok(seen.length > 3 && seen[seen.length - 1] === 1)
})

test('findCueIndex: before first, exact, inside gap, after last', () => {
  const cues = [{ start: 1 }, { start: 5 }, { start: 5 }, { start: 9 }]
  assert.equal(findCueIndex(cues, 0), -1)
  assert.equal(findCueIndex(cues, 1), 0)
  assert.equal(findCueIndex(cues, 4.99), 0)
  assert.equal(findCueIndex(cues, 5), 2)
  assert.equal(findCueIndex(cues, 8), 2)
  assert.equal(findCueIndex(cues, 1e9), 3)
  assert.equal(findCueIndex([], 3), -1)
})

test('findCueIndex is fast on a 60k cue transcript', () => {
  const cues = Array.from({ length: 60000 }, (_, i) => ({ start: i * 1.5 }))
  const t0 = performance.now()
  for (let i = 0; i < 100000; i++) findCueIndex(cues, (i * 7.3) % 90000)
  assert.ok(performance.now() - t0 < 500)
  assert.equal(findCueIndex(cues, 1.5 * 41234 + 0.1), 41234)
})

test('findWordIndex', () => {
  const { cues } = parseTranscript(VTT)
  assert.equal(findWordIndex(cues[0], 0.5), -1)
  assert.equal(findWordIndex(cues[0], 1.0), 0)
  assert.equal(findWordIndex(cues[0], 1.7), 1)
  assert.equal(findWordIndex(cues[0], 99), 3)
  assert.equal(findWordIndex(cues[1], 5), -1)
})

test('searchCues is case-insensitive and capped', () => {
  const cues = [{ text: 'The Dursleys' }, { text: 'nothing' }, { text: 'dursley again' }]
  assert.deepEqual(searchCues(cues, 'DURSLEY'), [0, 2])
  assert.deepEqual(searchCues(cues, 'dursley', 1), [0])
  assert.deepEqual(searchCues(cues, '  '), [])
})

test('offset and merge place per-file transcripts on the book timeline', () => {
  const a = parseTranscript('WEBVTT\n\n00:00:01.000 --> 00:00:02.000\nA <00:00:01.500>b').cues
  const b = parseTranscript('WEBVTT\n\n00:00:00.500 --> 00:00:01.000\nc').cues
  const merged = mergeCues([offsetCues(a, 0), offsetCues(b, 100)])
  assert.deepEqual(
    merged.map((c) => [c.start, c.text]),
    [
      [1, 'A b'],
      [100.5, 'c']
    ]
  )
  assert.equal(offsetCues(a, 10)[0].words[1].t, 11.5)
  assert.equal(a[0].start, 1) // input not mutated
})

test('pickTranscriptSources: single file, vtt preferred over srt', () => {
  const item = {
    libraryFiles: [
      { ino: '1', metadata: { filename: 'Book.m4b', relPath: 'Book.m4b', ext: '.m4b' } },
      { ino: '2', metadata: { filename: 'Book.srt', relPath: 'Book.srt', ext: '.srt' } },
      { ino: '3', metadata: { filename: 'Book.vtt', relPath: 'Book.vtt', ext: '.VTT' } }
    ],
    media: { audioFiles: [{ index: 1, duration: 100, metadata: { relPath: 'Book.m4b' } }] }
  }
  assert.deepEqual(pickTranscriptSources(item), [{ ino: '3', filename: 'Book.vtt', ext: '.vtt', offset: 0 }])
})

test('pickTranscriptSources: multi-file maps by basename with cumulative offsets, skips excluded', () => {
  const af = (index, dur, rel, extra = {}) => ({ index, duration: dur, metadata: { relPath: rel }, ...extra })
  const item = {
    libraryFiles: [
      { ino: '11', metadata: { filename: 'cd1 - 01.vtt', relPath: 'CD1/01.vtt', ext: '.vtt' } },
      { ino: '12', metadata: { filename: '03.srt', relPath: 'CD1/03.srt', ext: '.srt' } }
    ],
    media: { audioFiles: [af(3, 30, 'CD1/03.mp3'), af(1, 10, 'CD1/01.mp3'), af(2, 20, 'CD1/02.mp3', { exclude: true })] }
  }
  assert.deepEqual(
    pickTranscriptSources(item).map((s) => [s.ino, s.offset]),
    [
      ['11', 0],
      ['12', 10]
    ]
  )
})

test('pickTranscriptSources: lone sidecar with different name falls back for single-file books only', () => {
  const lib = [{ ino: '9', metadata: { filename: 'x.vtt', relPath: 'x.vtt', ext: '.vtt' } }]
  const one = { libraryFiles: lib, media: { audioFiles: [{ index: 1, duration: 5, metadata: { relPath: 'y.m4b' } }] } }
  assert.equal(pickTranscriptSources(one).length, 1)
  const two = { libraryFiles: lib, media: { audioFiles: [{ index: 1, duration: 5, metadata: { relPath: 'y.m4b' } }, { index: 2, duration: 5, metadata: { relPath: 'z.m4b' } }] } }
  assert.equal(pickTranscriptSources(two).length, 0)
  assert.deepEqual(pickTranscriptSources({ libraryFiles: [], media: { audioFiles: [] } }), [])
  assert.deepEqual(pickTranscriptSources(null), [])
})

test('formatClock', () => {
  assert.equal(formatClock(65), '1:05')
  assert.equal(formatClock(3725), '1:02:05')
  assert.equal(formatClock(-3), '0:00')
})
